server:
  port: 6015

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/Product
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true